#+options: num:nil toc:nil author:nil html-postamble:nil
# Sourcehut HTML renderer will render <style>: remove it
#+options: html-style:nil

#+title: org-transclusion-http

Transclude content over HTTP in Org mode with [[https://nobiot.github.io/org-transclusion/][org-transclusion]]!

* Installation

** Dependencies

~org-transclusion-http~ uses [[https://pandoc.org/][Pandoc]] to render HTML content as Org mode,
so to make full use of this package please ensure that the ~pandoc~
command is installed and in your ~PATH~.

** package-vc

#+begin_src emacs-lisp
  (unless (package-installed-p 'org-transclusion-http)
    (package-vc-install "https://git.sr.ht/~ushin/org-transclusion-http"))
#+end_src

* Usage

Add an ~org-transclusion~ link to an Org mode buffer:

#+begin_example
#+transclude: [[https://ushin.org/software.html]]
#+end_example

Then move point onto the link, and run ~M-x org-transclusion-add~.  Emacs
will download the webpage and convert its HTML content to Org mode
with Pandoc before displaying as an Org subtree in the same buffer.

~org-transclusion-http~ also handles non-HTML content, which will be
rendered as-is.

For more information on ~org-transclusion~, please see the [[https://nobiot.github.io/org-transclusion/][~org-transclusion~ manual]].

** Transclude only content at HTML link fragment

When the ~#+transclude:~ link contains a link fragment, also known as an
anchor or target, ~org-transclusion-http~ attempts to guess which HTML
element(s) to transclude:

#+begin_example
#+transclude: [[https://ushin.org/needs-list.html#care]] # Just "Care" subtree
#+transclude: [[https://ushin.org/needs-list.html]]      # Whole file
#+end_example

To improve ~org-transclusion~'s ability to determine which HTML elements
to transclude based on the element its link fragment points to, please
patch the ~org-transclusion-html.el~ file in ~org-transclusion~ itself.

For more usage examples, please see the tests.

* Limitations

Certain features of ~org-transclusion~, such as live-syncing and opening
source buffers, are not supported.

~:lines~ are not yet supported.  Patches welcome!

* Bugs and Patches

Bugs can be submitted to the [[https://todo.sr.ht/~ushin/ushin][ushin issue tracker]].  Patches, comments or
questions can be submitted to the [[https://lists.sr.ht/~ushin/ushin][ushin public inbox]].

* Changelog

** pre-0.2

Nothing yet...

** 0.1

Initial release.
